[build]
  publish = "dist/"

[context.production.processing]
  skip_processing = false
[context.production.processing.css]
  bundle = true
  minify = true
[context.production.processing.html]
  pretty_urls = true
[context.production.processing.images]
  compress = true

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://dev-nicolaos.netlify.com/*"
  to = "https://nicolaos.dev/:splat"
  status = 301
  force = true
