# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://nicolaos-dot-dev.netlify.com/*"
  to = "https://nicolaos.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
