name: CI

on:
    pull_request:
        branches: [main]

jobs:
    check-formating:
        runs-on: ubuntu-latest

        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"

            - name: Install NPM packages
              run: npm ci

            - name: Check formatting
              run: npm run check-formatting

	build:
		runs-on: ubuntu-latest

        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"

            - name: Install NPM packages
              run: npm ci

            - name: Build site
              run: npm run build
