name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-formating:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Check formatting
        run: npm run check-formatting
